This is PHCtool.
This release is completely written in Python using GTK.

PHCtool is a GUI for Linux-PHC (Processor Hardware Control).
Using this tool you can easily set up VIDs (Voltage IDs) to your CPUs and let them automatically being restored every time you restart your computer. Also PHCtool can throttle your CPU and verify whether your VIDs are used or not.

Notice: 
The linux-PHC patch tries to prevent you from setting wrong and destructable values but like every software nothing is perfect. 
You should be very careful with everything you do!

The linux-PHC project needs developers, testers and documentation writers!
Go to http://www.linux-phc.org/

To report errors or send patches to PHCtool please use the forum http://www.linux-phc.org/ or submit a comment to http://linuxsolver.blogspot.com
