In this Info page you can see the most important information about your system in context of linux-PHC.
Here you see if linux-PHC is detected on your system and what version you are using.
You can also see if PHCtool can read MSR informations, if throttling is available and if PHCtool knows your CPU.
If PHCtool doesn't know your CPU this is not a problem, PHCtool will just be unable to calculate voltages from the VIDs but it's for human readability only.
