Throttling a CPU means that you force the CPU to stay in sleep states for a while (depending on the state you set).
This is primary used to keep the CPU cooler but will reduce your CPUs power nearly 1:1.
If you throttle 50% your CPU will run 50% lower.
Most CPUs throttle themselves if they are too hot. These are other throttles than PHCtool use so you don't have to fear 
to override such critical settings. If your CPU gets too hot it will throttle no matter what you set here.
