#!/bin/bash

# WARNA
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'
clear


if [ $# -eq 0 ]
  then
	echo -ne "\t== Created by berrabe ==\n\n"

	echo " ==============="
	echo " |  Help Page  |"
	echo " ==============="

	echo -e "\n${LIGHTCYAN} [+] Monitoring"
	echo -e "  |=> Param \n\t|=> util [-m / --monitoring] [delay in second]"
	echo -e "  |=> Example \n\t|=> util -m 1${NOCOLOR}"

	echo -e "\n${LIGHTGREEN} [+] Set Frequency"
	echo -e "  |=> Param \n\t=> util [-sf / --set-freq] [number of cores] [frequency in MHz]"
	echo -e "  |=> Example \n\t=> util -sf 4 1200000${NOCOLOR}"

	echo -e "\n${WHITE} [+] Current Frequency"
	echo -e "  |=> Param \n\t=> util [-cf / --curr-freq] [number of cores]"
	echo -e "  |=> Example \n\t=> util -cf 4${NOCOLOR}"

    exit

elif [[ $1 == "-m" || $1 == "--monitoring" ]]
  then
    while true
	do
		temp=$(sensors | egrep "Core [0-7]" | sed -r 's/.*:\s+[\+-]?(.*C)\s+.*/\1/' | tr '\n' ' ')
		cpu=$(cat /proc/cpuinfo | grep -i "cpu MHz" | cut -b 12-20 | tr '\n' ' ')
		memory=$(awk '/^Mem/ {print $3}' <(free -m))

    echo -e "${WHITE}[TEMP]${NOCOLOR}${LIGHTGREEN} $temp${NOCOLOR}"
    echo -e "${WHITE}[FREQ]${NOCOLOR}${YELLOW} $cpu${NOCOLOR}"
    echo -e "${WHITE}[MEM]${NOCOLOR}${LIGHTPURPLE}  $memory${NOCOLOR}"
		sleep $2
    clear
	done


elif [[ $1 == "-sf" || $1 == "--set-freq" ]]
  then

	core="$(($2-1))"

	for i in $(seq 0 $core)
	do

		if [ ! -d "/sys/devices/system/cpu/cpu$i/cpufreq/" ]
		then 
			echo -e "\n[!] end of core"
			break
		fi

		echo $3 | sudo tee "/sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq"
	done


elif [[ $1 == "-cf" || $1 == "--curr-freq" ]]
  then

	core="$(($2-1))"

	for i in $(seq 0 $core)
	do

		if [ ! -d "/sys/devices/system/cpu/cpu$i/cpufreq/" ]
		then 
			echo -e "\n[!] end of core"
			break
		fi

		buffer=$(cat "/sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')
		echo "Max Freq Core $i = $buffer GHz"
	done


else
	echo "ERROR"

fi


