'\" t
.\"     Title: i3-input
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 01/30/2020
.\"    Manual: i3 Manual
.\"    Source: i3 4.16.1
.\"  Language: English
.\"
.TH "I3\-INPUT" "1" "01/30/2020" "i3 4\&.16\&.1" "i3 Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
i3-input \- interactively take a command for i3 window manager
.SH "SYNOPSIS"
.sp
i3\-input [\-s <socket>] [\-F <format>] [\-l <limit>] [\-P <prompt>] [\-f <font>] [\-v]
.SH "DESCRIPTION"
.sp
i3\-input is a tool to take commands (or parts of a command) composed by the user, and send it/them to i3\&. This is useful, for example, for the mark/goto command\&.
.sp
You can press Escape to close i3\-input without sending any commands\&.
.SH "OPTIONS"
.PP
\-s <socket>
.RS 4
Specify the path to the i3 IPC socket (it should not be necessary to use this option, i3\-input will figure out the path on its own)\&.
.RE
.PP
\-F <format>
.RS 4
Every occurrence of "%s" in the <format> string is replaced by the user input, and the result is sent to i3 as a command\&. Default value is "%s"\&.
.RE
.PP
\-l <limit>
.RS 4
Set the maximum allowed length of the user input to <limit> characters\&. i3\-input will automatically issue the command when the user input reaches that length\&.
.RE
.PP
\-P <prompt>
.RS 4
Display the <prompt> string in front of user input text field\&. The prompt string is not included in the user input/command\&.
.RE
.PP
\-f <font>
.RS 4
Use the specified X11 core font (use
xfontsel
to chose a font)\&.
.RE
.PP
\-v
.RS 4
Show version and exit\&.
.RE
.SH "EXAMPLES"
.sp
Mark a container with a single character:
.sp
.if n \{\
.RS 4
.\}
.nf
i3\-input \-F \*(Aqmark %s\*(Aq \-l 1 \-P \*(AqMark: \*(Aq
.fi
.if n \{\
.RE
.\}
.sp
Go to the container marked with above example:
.sp
.if n \{\
.RS 4
.\}
.nf
i3\-input \-F \*(Aq[con_mark="%s"] focus\*(Aq \-l 1 \-P \*(AqGo to: \*(Aq
.fi
.if n \{\
.RE
.\}
.SH "ENVIRONMENT"
.SS "I3SOCK"
.sp
i3\-input handles the different sources of socket paths in the following order:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
I3SOCK environment variable
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
I3SOCK gets overwritten by the \-s parameter, if specified
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
if neither are available, i3\-input reads the socket path from the X11 property, which is the recommended way
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
if everything fails, i3\-input tries
/tmp/i3\-ipc\&.sock
.RE
.sp
The socket path is necessary to connect to i3 and actually issue the command\&.
.SH "SEE ALSO"
.sp
i3(1)
.SH "AUTHOR"
.sp
Michael Stapelberg and contributors
