'\" t
.\"     Title: i3-nagbar
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 01/30/2020
.\"    Manual: i3 Manual
.\"    Source: i3 4.16.1
.\"  Language: English
.\"
.TH "I3\-NAGBAR" "1" "01/30/2020" "i3 4\&.16\&.1" "i3 Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
i3-nagbar \- displays an error bar on top of your screen
.SH "SYNOPSIS"
.sp
i3\-nagbar [\-m <message>] [\-b <button> <action>] [\-B <button> <action>] [\-t warning|error] [\-f <font>] [\-v]
.SH "OPTIONS"
.PP
\fB\-v, \-\-version\fR
.RS 4
Display version number and exit\&.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Display a short help\-message and exit\&.
.RE
.PP
\fB\-t, \-\-type\fR \fItype\fR
.RS 4
Display either a warning or error message\&. This only changes the color scheme for the i3\-nagbar\&. Default: error\&.
.RE
.PP
\fB\-m, \-\-message\fR \fImessage\fR
.RS 4
Display
\fImessage\fR
as text on the left of the i3\-nagbar\&.
.RE
.PP
\fB\-f, \-\-font\fR \fIfont\fR
.RS 4
Select font that is being used\&.
.RE
.PP
\fB\-b, \-\-button\fR \fIbutton\fR \fIaction\fR
.RS 4
Create a button with text
\fIbutton\fR\&. The
\fIaction\fR
are the shell commands that will be executed by this button\&. Multiple buttons can be defined\&. Will launch the shell commands inside a terminal emulator, using i3\-sensible\-terminal\&.
.RE
.PP
\fB\-B, \-\-button\-no\-terminal\fR \fIbutton\fR \fIaction\fR
.RS 4
Same as above, but will execute the shell commands directly, without launching a terminal emulator\&.
.RE
.SH "DESCRIPTION"
.sp
i3\-nagbar is used by i3 to tell you about errors in your configuration file (for example)\&. While these errors are logged to the logfile (if any), the past has proven that users are either not aware of their logfile or do not check it after modifying the configuration file\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
i3\-nagbar \-m \*(AqYou have an error in your i3 config file!\*(Aq \e
\-b \*(Aqedit config\*(Aq \*(Aqi3\-sensible\-editor ~/\&.config/i3/config\*(Aq
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
i3(1)
.SH "AUTHOR"
.sp
Michael Stapelberg and contributors
